### ISSUE TITLE
Splitting a string into multiple lines

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/plugin-intellij#14]
Currently when splitting a string in to multiple lines, we need to manually add the quotes and the "+" sign. It would be great if the IDE plugins can support automatically adding those for the following cases:
1. Pressing 'Enter' in the middle of the string
2. Formatting the source code
3. Automatically wrapping the lines

**Comment by NipunaRanasinghe** [comment]
Closing since this feature has already been added.
