### ISSUE TITLE
Working with latest Ballerina version in IDEA

### ISSUE THREAD

**Issue by scheung38** [ballerina-platform/plugin-intellij#23]
ballerina version
jBallerina 1.2.4
Language specification 2020R1
Update Tool 0.8.8
but inside IDEA it is still autodetecting 1.0.0? as I am aware strand notation is only available for later versions ?

Mac OS: Catalina 10.15.5

**Comment by anupama-pathirage** [comment]
Closing the issue as per the above comment. @scheung38 Please feel free to reopen if you still get the issue.
