### ISSUE TITLE
Introduce program execution and testing support for Ballerina Swan Lake versions

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/plugin-intellij#46]
**Description:**
$subject is planned to be done by detecting the system ballerina sdk path and executing ballerina commands through UI features in Intellij IDE. Also planned to add a language settings page for ballerina language and users can switch between system default ballerina version and other ballerina versions available in the system.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/plugin-intellij/pull/47
