### ISSUE TITLE
Introduce language server support for Ballerina Swan Lake versions

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/plugin-intellij#48]
**Description:**
$subject is planned to be implemented with the use of [lsp4intellij](https://github.com/ballerina-platform/lsp4intellij) language server client library. This will add the following features to the plugin that will use the Ballerina language server.
- Code Completion (with code snippet support)
- Code Formatting
- Diagnostics
- Code Actions
- Go to Definition
- Goto References / Find Usages
- Hover Support
- Renaming Support

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing as completed with https://github.com/ballerina-platform/plugin-intellij/pull/49
