### ISSUE TITLE
Add language server settings page for Swan Lake plugin versions

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/plugin-intellij#51]
**Description:**
Ballerina Language server provides various features that the user can enable or disable when using the plugin. A language settings page component is required to enable and disable these features and communicate them with the language server.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/plugin-intellij/pull/52
