### ISSUE TITLE
Add code folding regions support for Swan Lake plugin versions

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/plugin-intellij#53]
**Description:**
$subject

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/plugin-intellij/pull/54
