### ISSUE TITLE
Add highlighting identifiers which have the same name

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/plugin-intellij#55]
**Description:**
Highlight the same identifiers in the file and add location information to the error stripe when the caret is on an identifier element.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/plugin-intellij/pull/56
