### ISSUE TITLE
Add option to create new ballerina files in swan lake plugin versions

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/plugin-intellij#63]
**Description:**
Create new ballerina files in a right click action. Add option to create service template and main function template.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/plugin-intellij/pull/64
