### ISSUE TITLE
Add a spellchecker for swan lake plugin versions

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/plugin-intellij#65]
**Description:**
Add a spellchecker to check and indicate spelling errors for identifiers, comments and markdown documentation text.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/plugin-intellij/pull/66
