### ISSUE TITLE
Update documentation of the swan lake plugin versions.

### ISSUE THREAD

**Issue by ThemiraChathumina** [ballerina-platform/plugin-intellij#68]
**Description:**
Add the new features and SDK selection options to the plugin documentation.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/plugin-intellij/pull/69
